export const tml2025Artists = [
  '1991',
  '3 are legend',
  '3amdisco',
  '6EJOU (Live)',
  'A-Tom-X',
  'Aaron Hibell',
  'Aaron Sevilla',
  'Abel The Kid',
  'Abena',
  'Acid Asian',
  'Adam Beyer',
  'ADAM K',
  'Adrenalize',
  'Afrojack',
  'Agents of Time',
  'Airod',
  'Ajna',
  'AK Sports',
  'Alan Walker',
  'Albert Harvey',
  'Alex Kennon',
  'Alex Wann',
  'Alexander Popov',
  'ALOK',
  'Alure',
  'Amber Broos',
  'Âme (Live)',
  'Amelie Lens',
  'Ampe',
  'Anders',
  'Andromedik',
  'Andy C',
  'Angemi',
  'Anii',
  'ANNA',
  'Annabel Stop It',
  'Antdot',
  'Anyma',
  'Arado',
  'Argy',
  'ARKADYAN',
  'Armin van Buuren',
  'Artbat',
  'Artbat b2b Kölsch',
  'Arthur Lewis & Gerben Tuerlinckx',
  'Até & Salin',
  'Audiowave',
  'Axel Haube',
  'Axwell',
  'Azyr',
  'B Jones',
  'B_Type',
  'B"Elle',
  'Bad Boombox',
  'Baka G',
  'Ballantine',
  'Bashir',
  'Bassjackers',
  'Basstripper',
  'Basswell',
  'BAVR',
  'Bazzy',
  'BEBA STORM',
  'Belgianly Made',
  'Ben Böhmer',
  'Ben Malone',
  'Benny',
  'Bhaskar',
  'Bibi Seck',
  'Bingo Players',
  'BL3SS',
  'Blasterjaxx',
  'Blastoyz',
  'Blazy',
  'Block & Crown',
  'Blond:ish',
  'Bobbi Antonni',
  'Bobby & Djenko',
  'Bonzai All Stars',
  'Bora Uzer',
  'Boris Brejcha',
  'Brennan Heart',
  'BRESH',
  'Brian Cross & DJ Nano',
  'Bridgeman',
  'Brina Knauss',
  'Brooke Bailey',
  'Broz',
  'BYØRN',
  'C-Track',
  'Camo & Krooked',
  'Capoon',
  'Captain Bass',
  'Carla Genus',
  'Carlita',
  'Carly Wilford',
  'CARV',
  'Cassian b2b Kevin de Vries',
  'Cat Dealers',
  'Cence Brothers',
  'CHAM',
  'Charlotte de Witte',
  'Chris Avantgarde',
  'Christophe',
  'Christophe b2b Seelen',
  'Clara Cuvé',
  'Cleopard2000',
  'Cloudy',
  'Coco Bevan',
  'Coone',
  'Crankdat',
  'Cristiano Da Silva',
  'Cromanty Sound',
  'Curol',
  'Curses',
  'Cyril',
  'D. Guaetta',
  'Da Tweekaz',
  'Damian Lazarus',
  'Dana Montana',
  'Dannic',
  'Dannic x Dyro',
  'Dany Neville',
  'Darren Styles',
  'Dave Lambert',
  'David DM',
  'David Guetta',
  'Daybreak: Arielle Free b2b Sam Divine',
  'Daybreak: Bob Sinclar & Paloma b2b',
  'Daybreak: Push',
  'Daybreak: Yves V',
  'De Jaren Nul Party',
  'Deadly Guns',
  'Deepesh Sharma b2b Omnaya',
  'Delafino',
  'Demi Kanon',
  'Deuxfwa',
  'Diego Miranda',
  'Dieux Pere',
  'Diffrent',
  'Dillon Francis',
  'Dimitri Vegas',
  'Dimitri Vegas (vinyl set)',
  'Dimitri Vegas & Like Mike',
  'Dino Lenny',
  'Dirtyphonics',
  'Disco Dasco',
  'Diskobar Sabrina',
  'Dixon',
  'DJ Battery',
  'DJ BORING',
  'DJ F.R.A.N.K',
  'DJ Furax',
  'DJ Gee',
  'DJ Ghost',
  'DJ Gigola',
  'DJ Jan',
  'DJ Kurt',
  'DJ Licious',
  'DJ Phantasy',
  'DJ Philip',
  'DJ Quicksilver',
  'DJ Tennis',
  'DJ Ward',
  'DJ Wout',
  'Dokho',
  'Domi Re',
  'Double D',
  'Dr Donk',
  'Drezz',
  'Drissque',
  'DRS',
  'Dual Damage',
  'Dub Elements',
  'Dubdogz',
  'Dubvision',
  'DVBBS',
  'DYEN',
  'Dyzen',
  'Eddiethehost',
  'Effy',
  'Eli Brown',
  'Eli Rojas',
  'ELIF',
  'EMILIJA',
  'Emily Makis',
  'Emjie',
  'Encore Soundsystem',
  'Eptic',
  'Equal2',
  'Eric Prydz',
  'Erykah',
  'Esin Boz & Bastin',
  'Eskei83',
  'Eva Vrijdag',
  'F.NOIZE',
  'Fabio Fusco',
  'Faisal',
  'Fantasm',
  'Faster horses',
  'Fedde Le Grand',
  'Fideles',
  'Fiesta Macumba Soundsystem',
  'Firaga',
  'Firebeatz',
  'Fisher',
  'FJAAK',
  'FKA.M4A',
  'FLASH',
  'Flavour Drop',
  'Flo Windey & Skyve',
  'Flowchief',
  'FONSI NIETO',
  'Franky Kloeck',
  'Ftampa',
  'Funk Tribu',
  'Galactixx',
  'Geheimzinnig Soundsystem',
  'Gino',
  'Gomorris',
  'Gordo',
  'Greg S',
  'Guilini',
  'HAAi',
  'Hannah Laing',
  'Hard Driver',
  'Hardwell',
  'HAWKEYS',
  'Hayve',
  'Helena Lauwaert',
  'Henri PFR',
  'HI-LO',
  'Hi-Profile',
  'Hide N Seek',
  'Holy Priest',
  'Hunter',
  'Hurts',
  'Hyalyte',
  'I Hate Models',
  'Ida Engberg',
  'Idle Days',
  'Illusionize',
  'Imhappy',
  'Indira Paganotto',
  'Infekt',
  'Innellea',
  'IRWAN ft. RICO GREENE',
  'IVY',
  'J. Roots',
  'J8man',
  'Jade Soul',
  'Jaden Bojsen',
  'Jaël Ost & MagiK',
  'Jahwin',
  'James Carter',
  'James de Torres',
  'James Hype',
  'Jan Vervloet',
  'Jana Vitiligo',
  'Jane Muss',
  'Jax Jones',
  'Jazzy',
  'Jeroen Delodder',
  'Jeronimø',
  'Jess Bays',
  'Jessica Brankka',
  'Jimi Jules',
  'Job Jobse',
  'Joel Corry',
  'Joezi',
  'John Newman',
  'John Summit',
  'Jonas van Opstal',
  'Joris Voorn',
  'Jorn Pricez',
  'JOULIE',
  'Joy Orbison',
  'JOYSE',
  'Junkie Kid',
  'JUSTANOTHERDJ',
  'Justin Hawkes',
  'Justin Wilkes',
  'Kane',
  'Kasia',
  'Katy Rough',
  'KD Soundsystem',
  'Kenn Colt',
  'Kento',
  'Kevin de Vries',
  'Kirollus',
  'Kitty Amor',
  'Klaps',
  'Kneiz',
  'Kölsch',
  'Kompass Traxx',
  'Konstantin Sibold',
  'Korolova',
  'Kriss Reeve',
  'Kryder',
  'Latu',
  'Laura Hoogland',
  'Laura Meester',
  'Laurens Luyten',
  'LB aka LABAT',
  'Lee Ann Roberts',
  'Legolane',
  'Lena De Roose',
  'Lennert Wolfs',
  'Like Mike',
  'LIMITLEZZ',
  'Liu',
  'LNY TNZ',
  'Los Bomberos',
  'Lost Frequencies',
  'Lotte Feyen',
  'Lovely Louis',
  'LOW E',
  'LSDXOXO',
  'Lucca van Damme',
  'Luna & Lenthe',
  'Luna Fields',
  'Luna Fino',
  'Maddix',
  'MagiK',
  'Mahmut Orhan',
  'Mairee',
  'Malugi',
  'MANDY',
  'Manuals',
  'Marhu',
  'Mariah Curry',
  'Marianna Bo',
  'Marijn Jansen',
  'Mark Roma',
  'Mark With a K',
  'Mars',
  'Marten Hørger',
  'Marten Lou',
  'Martin Garrix',
  'Massano',
  'Mathame',
  'Matisse & Sadko',
  'MATTN',
  'Max Styler',
  'Maxtreme',
  'Maze',
  'MC Brunograffer',
  'MC Rim',
  'MC Villain',
  'Meaghan',
  'Meduza',
  'Meguru',
  'Mekkanikka',
  'MELV!EE',
  'MËRO',
  'Metrik',
  'Miamor',
  'Mike Mago',
  'Milinguap',
  'MĪMĪ x FY',
  'Mind Against',
  'MIRO',
  'Miss Monique',
  'MITCHED',
  'Mixturess',
  'MK',
  'MOGUAI',
  'Monta',
  'More to be announced',
  'Moritz Hofbauer',
  'MORTEN',
  'Mosoo',
  'MOTi',
  'Mr. Belt & Wezol',
  'Mr. Joy',
  'Mr. Rewind',
  'Murdock',
  'Mutilator',
  'Muze',
  'Naomi Cazier',
  'Nayla',
  'NC',
  'Nederhand',
  'Negitiv',
  'Neon',
  'NERVO',
  'Netsky',
  'NGHTMRE',
  'Nicky Romero',
  'Nico Moreno',
  'Nico Parisi',
  'Nightfunk',
  'Niklas Dee',
  'Nina Black',
  'Noaffection',
  'Noiseflow',
  'NOME.',
  'Nora En Pure',
  'NOVAH',
  'Noxiouz',
  'NRKi',
  'Oden & Fatzo (Live)',
  'Odssey',
  'Odymel',
  'Ogazon',
  'Oliver Heldens',
  'Olympe',
  'OM3N',
  'Omdat Het Kan & Average Rob',
  'One87',
  'Onlynumbers',
  'Onyvaa',
  'Oriol Calvo',
  'Oscar and the Wolf (After Hours)',
  'Pako Marckx',
  'Palmera',
  'Parallelle',
  'Party Monster',
  'Partyraiser',
  'Pat B',
  'Pat Krimson',
  'Patrick Mason',
  'Patrick Mason (house set)',
  'Pegassi',
  'Phi Phi',
  'Phuture Traxx',
  'Pinotello',
  'Pirapus',
  'Portex',
  'Pricila Diaz',
  'Primate',
  'Prinsezy',
  'Prospa',
  'Push',
  'R3HAB',
  'Rafi Khan',
  'Rayzen',
  'Re-Twin',
  'Rebelion',
  'Refuzion',
  'Regi',
  'Revedge',
  'Revenja',
  'Rewind Allstars',
  'Reygel',
  'Rick & James 80’s Party',
  'Riot Ten',
  'Rivo',
  'Robin Schulz',
  'Rockefellababe',
  'Roma',
  'Roman Messer',
  'Roman Weber',
  'Romy Janssen',
  'Rose Ringed',
  'RPTR',
  'RUBY XX',
  'Ruth Royall',
  'Ruze',
  'Ryan Spicer',
  'Sacha Malice',
  'Sako Glitch',
  'Sakyra',
  'Sam Feldt',
  'Sam Hofman',
  'Samm',
  'Sander van Doorn',
  'Sandy Warez',
  'Sara Landry',
  'Sarah Story',
  'Satirized',
  'Séa',
  'Sebastian Ingrosso',
  'Seelen',
  'Sem Jacobs',
  'Semsei',
  'Sennix',
  'Serzo',
  'Shake Coconut',
  'Shapov',
  'SHE',
  'Shiverz',
  'Sicaria',
  'Sideral',
  'Sigala',
  'Sim0ne',
  'Skazi',
  'Skytech',
  'Skyve',
  'Slatin',
  'Sofi Tukker',
  'Solomun',
  'Som Systema',
  'Somnia.',
  'Sonny Fodera',
  'SOTA',
  'Soul Shakers',
  'Soulcity',
  'Sound Rush',
  'Space92',
  'Sparrow & Barbossa',
  'SPFDJ',
  'Spitnoise',
  'Steve Angello',
  'Steve Aoki',
  'Stijn VM',
  'Stryker',
  'Sub Focus',
  'Sub Zero Project',
  'Sunnery James & Ryan Marciano',
  'Supergloss',
  'Superheroes (Laidback Luke Presents Super You & Me)',
  'Suttlek',
  'Swedish House Mafia',
  'Swimming Paul',
  'Symphony of Unity',
  'T & Sugah',
  'Team DAMP',
  'Teddy Killerz',
  'Tess',
  'The Blessed Madonna',
  'The Dark Horror',
  'The Rocketman',
  'The Whatevers',
  'The Z.',
  'Third Party',
  'Thomas Newson',
  'Thomm',
  'Tim Hox',
  'Timmy Trumpet',
  'Titan',
  'TNT',
  'Tobi Trekhaak',
  'Tola OG ft. Henok',
  'Toolate Groove',
  'Toone',
  'Toxic Twins',
  'Trip-Tamine',
  'TripleX & LeMarc',
  'Tripolism',
  'Troublemen',
  'TSHA',
  'Tungevaag',
  'Tweekacore x Gammer',
  'UNEAK',
  'Unicorn on K',
  'Unregular',
  'Unsyn',
  'USED',
  'Valentín Huedo',
  'Valentino',
  'VALENTINO IGNOTO',
  'Vegas',
  'Vera Moro',
  'Vernex',
  'VIDO',
  'Viktor',
  'Vini Vici',
  'Vintage Culture',
  'Vion Konger',
  'Vize',
  'VTSS',
  'Vunzige Deuntjes Soundsystem',
  'W4STD',
  'Walshy Fire',
  'Warface',
  'Webra',
  'WEF',
  'Whipped Cream',
  'WHITENO1SE',
  'Wildstylez',
  'Wiwek',
  'WUKI',
  'X-TOF',
  'X&Trick',
  'Yamo',
  'YERUN',
  'Young Fresh',
  'Yves Deruyter',
  'Yves V',
  'ZAC',
  'ZERB',
  'Zouzibabe',
  'ZT Music',
  'Zyce',
];
